language: python

services:
  - postgresql

python:
  - "3.7"

install:
  - pip install tox

before_script:
  - psql -c 'create database pokemon;' -U postgres

script:
  - tox

notifications:
  email: false
