# Generated by Django 3.1.2 on 2020-10-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('capture_rate', models.IntegerField()),
                ('color', models.CharField(max_length=80)),
                ('flavor_text', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('abilities', models.ManyToManyField(to='pokemons.Ability')),
                ('moves', models.ManyToManyField(to='pokemons.Move')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemons.pokemon')),
                ('type_statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.typestatistic')),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_default', models.URLField(blank=True, null=True)),
                ('back_female', models.URLField(blank=True, null=True)),
                ('back_shiny', models.URLField(blank=True, null=True)),
                ('back_shiny_female', models.URLField(blank=True, null=True)),
                ('front_default', models.URLField(blank=True, null=True)),
                ('front_female', models.URLField(blank=True, null=True)),
                ('front_shiny', models.URLField(blank=True, null=True)),
                ('front_shiny_female', models.URLField(blank=True, null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprites', to='pokemons.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemons.Type'),
        ),
    ]
